# Generated by Django 2.1.2 on 2018-10-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_html',
        ),
    ]
